# Generated by Django 4.2.3 on 2023-07-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='pay_method',
        ),
        migrations.AddField(
            model_name='orders',
            name='pay_method',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
