# Generated by Django 4.2.3 on 2023-07-16 09:06

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_orderdetails_pay_method_orders_pay_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='ContactNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='static/items/red_dress.jpg', upload_to=home.models.upload_location),
        ),
    ]
